project:
  type: website
  output-dir: docs
  pre-render: meta.R
  post-render: clean_meta.R

website:
  title: "TR"
  favicon: https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/i1rzctchpbjbcmdo60ar
  site-url: https://damien-dupre.github.io/
  description: "Statistics Slides"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@damien_dupre"
  navbar:
    left:
      - href: index.qmd
        icon: fas fa-home
        text: Home
      - about.qmd
  page-footer:
    left: "DCU Business School"
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

