project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!internal/"
  resources:
  - "assets/my-first-web-page.html"

website:
  title: "Damien Dupré"
  site-url: https://damien-dupre.github.io/
  favicon: assets/favicon.png
  description: "Research, Statistics, and Data Analytics"
  twitter-card:
    creator: "@damien_dupre"
  navbar:
    title: false
    logo: assets/logo.png
    right:
      - icon: file-post
        href: posts/index.qmd
        text: "POSTS"
      - icon: journal-bookmark-fill
        href: courses/index.qmd
        text: "COURSES"
      - icon: person-lines-fill
        href: about.qmd
        text: "ABOUT ME"
      - icon: file-earmark-person
        href: assets/cv_pro.pdf
        text: "CV"
        target: _blank
  page-footer:
    background: "#6C757D"
    center: |
      Damien Dupré - Research, Statistics, and Data Analytics<br>
      ![](https://business.dcu.ie/wp-content/uploads/2024/02/Web-Logo-2-340x79-1.webp)
      
format:
  html:
    theme: [cosmo, assets/custom.scss] 
    lightbox: true
    mainfont: Montserrat
    smooth-scroll: true
    toc: false

