project:
  type: website
  output-dir: docs
  pre-render: meta.R
  post-render: clean_meta.R

website:
  title: "TR"
  favicon: https://www.dcu.ie/sites/default/files/marketing/images/dcu_logo_stacked_red.eps
  site-url: https://damien-dupre.github.io/
  description: "Statistics Slides"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@damien_dupre"
  navbar:
    left:
      - href: index.qmd
        icon: fas fa-home
        text: Home
      - about.qmd
  page-footer:
    left: "DCU Business School"
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

