project:
  type: website
  output-dir: docs

website:
  title: "Teaching Repository"
  navbar:
    left:
      - href: index.qmd
        icon: fas fa-home
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

