project:
  type: website
  output-dir: docs

website:
  title: "Damien Dupré"
  site-url: https://damien-dupre.github.io/
  favicon: assets/favicon.svg
  description: "Research, Statistics, and Data Analytics"
  twitter-card:
    creator: "@damien_dupre"
  navbar:
    logo: assets/icon.jpg
    right:
      # - icon: file-post
      #   href: courses/index.qmd
      #   text: "POSTS"
      # - icon: chat-quote
      #   href: courses/index.qmd      
      #   text: "TALKS"
      # - icon: paperclip
      #   href: courses/index.qmd
      #   text: "PUBLICATIONS"
      - icon: journal-bookmark-fill
        href: courses/index.qmd
        text: "COURSES"
      - icon: person-lines-fill
        href: about.qmd
        text: "ABOUT ME"
      - icon: file-earmark-person
        href: cv_pro.pdf
        text: "CV"
      
format:
  html:
    theme: [cosmo, assets/custom.scss] 
    lightbox: true
    css: assets/styles.css
    mainfont: Montserrat
    smooth-scroll: true
    toc: false

