---
title: "MT611 - Quantitative Research Methods"
---

This module has been designed to help you improve your understanding of the key quantitative tools and statistical analyses for social science and business research. To start you will explore the key concepts and issues in measurement, focusing in particular on numeric variables and multi-item scales. The main focus of the course is a study of the main data analysis techniques based on linear regressions and multivariate linear regressions. This will instruct you in statistical test selection using SPSS, JAMOVI (open-source alternative to SPSS) and R (short introduction). Finally the module will present how to interpret and to report the results of these tests. A key element of the course will be a study of several quantitative research study cases using multivariate techniques.

Link to the lecture slides:
- [Lecture 1](https://damien-dupre.github.io/mt611/lectures/lecture_1)
- [Lecture 2](https://damien-dupre.github.io/mt611/lectures/lecture_2)
- [Lecture 3](https://damien-dupre.github.io/mt611/lectures/lecture_3)
- [Lecture 4](https://damien-dupre.github.io/mt611/lectures/lecture_4)
- [Lecture 5](https://damien-dupre.github.io/mt611/lectures/lecture_5)
- [Lecture 6](https://damien-dupre.github.io/mt611/lectures/lecture_6)
- [Lecture 7](https://damien-dupre.github.io/mt611/lectures/lecture_7)
- [Lecture 8](https://damien-dupre.github.io/mt611/lectures/lecture_8)